import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { createMdocsCore } from '../../src/core';

function copyDir(source: string, target: string) {
  fs.mkdirSync(target, { recursive: true });
  for (const entry of fs.readdirSync(source, { withFileTypes: true })) {
    const sourcePath = path.join(source, entry.name);
    const targetPath = path.join(target, entry.name);
    if (entry.isDirectory()) copyDir(sourcePath, targetPath);
    else fs.copyFileSync(sourcePath, targetPath);
  }
}

function exactChildExists(parent: string, child: string): boolean {
  return fs.existsSync(parent) && fs.readdirSync(parent).includes(child);
}

const INGEST_OPS = [
  { type: 'createPage', category: 'decisions', id: 'd1', title: 'D1', content: 'decide X' },
  { type: 'updateOverviewSection', section: 'Status', body: 'green' },
  { type: 'appendLog', entry: 'shipped d1' }
];

describe('wiki.ingest directory-v2 byte-stable index contract', () => {
  test('external owner (dir-v2 default) leaves wiki/index.md byte-identical; overview.md/log.md produced', async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), 'harness-mdocs-dirv2-ingest-ext-'));
    const fixtureRoot = path.resolve(__dirname, '../fixtures/directory-v2-mdocs');
    copyDir(fixtureRoot, projectDir);

    const wikiDir = path.join(projectDir, 'mdocs', 'wiki');
    const wikiIndexPath = path.join(wikiDir, 'index.md');
    const overviewPath = path.join(wikiDir, 'overview.md');
    const logPath = path.join(wikiDir, 'log.md');

    const beforeIndex = fs.readFileSync(wikiIndexPath, 'utf8');

    // Default contract: canonical-lowercase + external owner (no opt-in).
    const core = createMdocsCore(projectDir);
    expect(core.managers.wiki['contract'].wikiIndexMode).toBe('canonical-lowercase');
    expect(core.managers.wiki['contract'].wikiIndexOwner).toBe('external');

    const result: any = await core.commands.execute('wiki.ingest', { operations: INGEST_OPS, note: 'dirv2-external' });

    // Manifest success and caller content landed.
    expect(result).toMatchObject({ success: true });
    expect(result.note).toBe('dirv2-external');

    // index.md byte-stable: identical bytes before and after.
    const afterIndex = fs.readFileSync(wikiIndexPath, 'utf8');
    expect(afterIndex).toBe(beforeIndex);
    // No uppercase INDEX.md materialized in canonical-lowercase mode.
    expect(exactChildExists(wikiDir, 'INDEX.md')).toBe(false);

    // Compiled views produced in both modes.
    expect(fs.existsSync(overviewPath)).toBe(true);
    expect(fs.existsSync(logPath)).toBe(true);
    const overview = fs.readFileSync(overviewPath, 'utf8');
    const log = fs.readFileSync(logPath, 'utf8');
    expect(overview).toContain('## Status');
    expect(overview).toContain('green');
    expect(log).toContain('shipped d1');

    // No-prose sanity: caller content is verbatim.
    const d1Path = path.join(wikiDir, 'decisions', 'd1.md');
    expect(fs.existsSync(d1Path)).toBe(true);
    expect(fs.readFileSync(d1Path, 'utf8')).toContain('decide X');
  });

  test('harness owner regenerates wiki/index.md to include new page/overview/log; still canonical lowercase', async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), 'harness-mdocs-dirv2-ingest-harness-'));
    const fixtureRoot = path.resolve(__dirname, '../fixtures/directory-v2-mdocs');
    copyDir(fixtureRoot, projectDir);

    const wikiDir = path.join(projectDir, 'mdocs', 'wiki');
    const wikiIndexPath = path.join(wikiDir, 'index.md');
    const overviewPath = path.join(wikiDir, 'overview.md');
    const logPath = path.join(wikiDir, 'log.md');

    const beforeIndex = fs.readFileSync(wikiIndexPath, 'utf8');

    // Opt-in: harness maintains the lowercase canonical index.
    const core = createMdocsCore(projectDir, { compatibility: { wikiIndexOwner: 'harness' } });
    expect(core.managers.wiki['contract'].wikiIndexMode).toBe('canonical-lowercase');
    expect(core.managers.wiki['contract'].wikiIndexOwner).toBe('harness');

    const result: any = await core.commands.execute('wiki.ingest', { operations: INGEST_OPS, note: 'dirv2-harness' });

    expect(result).toMatchObject({ success: true });
    expect(result.note).toBe('dirv2-harness');

    const afterIndex = fs.readFileSync(wikiIndexPath, 'utf8');
    // Regenerated by updateIndices -> CHANGED from the fixture placeholder.
    expect(afterIndex).not.toBe(beforeIndex);
    // Still parses as the canonical lowercase index format.
    expect(afterIndex.startsWith('# Wiki\n\n')).toBe(true);
    // The new page / compiled views appear in the regenerated index.
    expect(afterIndex).toContain('decisions/d1.md');
    expect(afterIndex).toContain('overview.md');
    expect(afterIndex).toContain('log.md');
    // The pre-existing fixture entry is preserved through regeneration.
    expect(afterIndex).toContain('- [System Page](systems/system-page.md)');
    // No uppercase INDEX.md materialized in canonical-lowercase mode.
    expect(exactChildExists(wikiDir, 'INDEX.md')).toBe(false);

    // Compiled views produced in both modes.
    expect(fs.existsSync(overviewPath)).toBe(true);
    expect(fs.existsSync(logPath)).toBe(true);
    expect(fs.readFileSync(overviewPath, 'utf8')).toContain('green');
    expect(fs.readFileSync(logPath, 'utf8')).toContain('shipped d1');

    // No-prose sanity: caller content is verbatim.
    const d1Path = path.join(wikiDir, 'decisions', 'd1.md');
    expect(fs.existsSync(d1Path)).toBe(true);
    expect(fs.readFileSync(d1Path, 'utf8')).toContain('decide X');
  });

  test('no-prose: created page body and overview section body equal exactly the caller text', async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), 'harness-mdocs-dirv2-ingest-noprose-'));
    const fixtureRoot = path.resolve(__dirname, '../fixtures/directory-v2-mdocs');
    copyDir(fixtureRoot, projectDir);

    const wikiDir = path.join(projectDir, 'mdocs', 'wiki');
    const core = createMdocsCore(projectDir);

    await core.commands.execute('wiki.ingest', { operations: INGEST_OPS });

    // Page body equals exactly the caller content (no synthesized prose).
    const d1 = fs.readFileSync(path.join(wikiDir, 'decisions', 'd1.md'), 'utf8');
    expect(d1).toContain('decide X');

    // Overview section body equals exactly the caller body up to the next heading.
    const overview = fs.readFileSync(path.join(wikiDir, 'overview.md'), 'utf8');
    const statusBlock = overview.split('## Status')[1] || '';
    const bodyAfterHeading = statusBlock.split('\n')[0] === '' ? statusBlock.split('\n').slice(1).join('\n') : statusBlock;
    const bodyUpToNext = bodyAfterHeading.split(/\n## /)[0];
    expect(bodyUpToNext.trim()).toBe('green');

    // Log entry equals exactly the caller text.
    const log = fs.readFileSync(path.join(wikiDir, 'log.md'), 'utf8');
    const logContentBlock = log.split(/## \d{4}-\d{2}-\d{2}T[\d:.Z+-]+\n\n/).pop() || '';
    expect(logContentBlock.trim()).toBe('shipped d1');
  });
});
