import * as fs from 'fs';
import * as path from 'path';
import { detectMdocsContract, MdocsCompatibilityConfig, MdocsContract } from '../contract';
import { parseFrontmatter, type WikiEntry } from '../types';

export interface WikiManagerOptions {
  standaloneCategories?: string[];
  compatibility?: MdocsCompatibilityConfig;
}

export class WikiManager {
  private dir: string;
  private standaloneCategories: Set<string>;
  private contract: MdocsContract;

  constructor(baseDir: string, options: WikiManagerOptions = {}) {
    this.dir = path.join(baseDir, 'wiki');
    this.standaloneCategories = new Set((options.standaloneCategories || []).map(category => this.sanitizeName(category)));
    this.contract = detectMdocsContract(baseDir, options.compatibility);
    fs.mkdirSync(this.dir, { recursive: true });
  }

  private toFrontmatter(entry: WikiEntry): string {
    const front: Record<string, any> = {
      id: entry.id,
      title: entry.title,
      category: entry.category,
      created: entry.created,
      updated: entry.updated,
      related_initiatives: entry.relatedInitiatives,
      tags: entry.tags,
    };
    if (entry.lifecycle) front.lifecycle = entry.lifecycle;
    if (entry.knowledgeType) front.knowledge_type = entry.knowledgeType;
    if (entry.confidence) front.confidence = entry.confidence;
    if (entry.sourceInitiatives && entry.sourceInitiatives.length > 0) front.source_initiatives = entry.sourceInitiatives;
    if (entry.supersedes && entry.supersedes.length > 0) front.supersedes = entry.supersedes;
    if (entry.relatedWiki && entry.relatedWiki.length > 0) front.related_wiki = entry.relatedWiki;
    return `---\n${Object.entries(front).map(([k, v]) => `${k}: ${JSON.stringify(v)}`).join('\n')}\n---\n\n`;
  }

  private sanitizeName(name: string): string {
    const base = path.basename(name);
    if (!base || base === '.' || base === '..') {
      throw new Error(`Invalid name: ${name}`);
    }
    return base;
  }

  private isRootCategory(category: string | undefined): boolean {
    return category === undefined || category === '';
  }

  private assertRootWritable(id: string): void {
    if (id.toLowerCase() === 'index' && this.contract.wikiIndexMode === 'canonical-lowercase') {
      throw new Error('Refusing to overwrite canonical root wiki index: index');
    }
  }

  private generateReferencedBySection(initiativeIds: string[]): string {
    if (initiativeIds.length === 0) return '';
    const lines = initiativeIds.map(id => `- ${id}`);
    return `\n\n## Referenced By\n\n*Auto-generated by mdocs*\n\n${lines.join('\n')}\n`;
  }

  private stripReferencedBySection(content: string): string {
    // Remove the auto-generated Referenced By section (everything from "\n\n## Referenced By" to end)
    const marker = '\n\n## Referenced By\n';
    const idx = content.indexOf(marker);
    if (idx !== -1) {
      return content.slice(0, idx);
    }
    return content;
  }

  private referencedByMarker = '\n\n## Referenced By\n';

  create(entry: WikiEntry): string {
    const id = this.sanitizeName(entry.id);
    if (this.isRootCategory(entry.category)) {
      this.assertRootWritable(id);
      const filePath = path.join(this.dir, `${id}.md`);
      const content = this.toFrontmatter({ ...entry, category: '' }) + entry.content + this.generateReferencedBySection(entry.relatedInitiatives);
      fs.writeFileSync(filePath, content, 'utf8');
      this.updateIndices();
      return filePath;
    }
    const category = this.sanitizeName(entry.category);
    const categoryDir = path.join(this.dir, category);
    fs.mkdirSync(categoryDir, { recursive: true });
    const filePath = path.join(categoryDir, `${id}.md`);
    const referencedBy = this.generateReferencedBySection(entry.relatedInitiatives);
    const content = this.toFrontmatter(entry) + entry.content + referencedBy;
    fs.writeFileSync(filePath, content, 'utf8');
    this.updateIndices();
    return filePath;
  }

  read(category: string, id: string): WikiEntry | null {
    const cat = this.sanitizeName(category);
    const entryId = this.sanitizeName(id);
    const filePath = path.join(this.dir, cat, `${entryId}.md`);
    if (!fs.existsSync(filePath)) return null;
    const content = fs.readFileSync(filePath, 'utf8');
    return this.parseWikiEntry(content);
  }

  readByRef(ref: string): WikiEntry | null {
    const parts = ref.split('/').filter(Boolean);
    if (parts.length === 1) return this.readRoot(parts[0]);
    if (parts[0] === '_obsidian') return null;
    if (parts.length === 2) return this.read(parts[0], parts[1].replace(/\.md$/, ''));
    return null;
  }

  refFor(entry: WikiEntry): string {
    if (entry.id && fs.existsSync(path.join(this.dir, `${entry.id}.md`))) return entry.id;
    return entry.category ? `${entry.category}/${entry.id}` : entry.id;
  }

  private readRoot(id: string): WikiEntry | null {
    const entryId = this.sanitizeName(id.replace(/\.md$/, ''));
    const filePath = path.join(this.dir, `${entryId}.md`);
    if (!fs.existsSync(filePath)) return null;
    const content = fs.readFileSync(filePath, 'utf8');
    return this.parseWikiEntry(content, { id: entryId, category: '' });
  }

  private parseWikiEntry(content: string, defaults: { id?: string; category?: string } = {}): WikiEntry {
    const front = parseFrontmatter(content);
    const hasFrontmatter = Object.keys(front).length > 0;
    if (!hasFrontmatter && !defaults.id) throw new Error('Invalid wiki entry format');

    let body = hasFrontmatter ? content.replace(/---\n[\s\S]*?\n---/, '').trim() : content.trim();
    body = this.stripReferencedBySection(body);
    const firstHeading = body.match(/^#\s+(.+)$/m)?.[1]?.trim();
    const fallbackTitle = firstHeading || (defaults.id ? defaults.id.replace(/[-_]+/g, ' ') : '');

    return {
      id: front.id || defaults.id || '',
      title: front.title || fallbackTitle,
      category: front.category || defaults.category || '',
      created: front.created || '',
      updated: front.updated || '',
      relatedInitiatives: Array.isArray(front.related_initiatives) ? front.related_initiatives : [],
      tags: Array.isArray(front.tags) ? front.tags : [],
      content: body,
      lifecycle: front.lifecycle || undefined,
      knowledgeType: front.knowledge_type || undefined,
      confidence: front.confidence || undefined,
      sourceInitiatives: Array.isArray(front.source_initiatives)
        ? front.source_initiatives
        : Array.isArray(front.sources)
          ? front.sources
          : undefined,
      supersedes: Array.isArray(front.supersedes) ? front.supersedes : undefined,
      relatedWiki: Array.isArray(front.related_wiki) ? front.related_wiki : undefined
    };
  }

  private parseRelatedWiki(content: string): string[] {
    const match = content.match(/---\n([\s\S]*?)\n---/);
    if (!match) return [];
    for (const line of match[1].split('\n')) {
      const [key, ...valueParts] = line.split(':');
      if (key?.trim() !== 'related_wiki' || valueParts.length === 0) continue;
      const value = valueParts.join(':').trim();
      try {
        const parsed = JSON.parse(value);
        return Array.isArray(parsed) ? parsed.filter((item): item is string => typeof item === 'string') : [];
      } catch {
        return [];
      }
    }
    return [];
  }

  private referencedWikiRefs(): Set<string> {
    const refs = new Set<string>();
    for (const filePath of this.listInitiativeFiles()) {
      try {
        const content = fs.readFileSync(filePath, 'utf8');
        for (const ref of this.parseRelatedWiki(content)) refs.add(ref);
      } catch {
        // Ignore unreadable initiative files; initiative validation reports them.
      }
    }
    return refs;
  }

  update(category: string, id: string, entry: WikiEntry): string {
    const entryId = this.sanitizeName(id);
    if (this.isRootCategory(category)) {
      this.assertRootWritable(entryId);
      const filePath = path.join(this.dir, `${entryId}.md`);
      if (!fs.existsSync(filePath)) throw new Error(`Wiki entry not found: ${entryId}`);
      entry.updated = new Date().toISOString().split('T')[0];
      const cleanContent = this.stripReferencedBySection(entry.content);
      const referencedBy = this.generateReferencedBySection(entry.relatedInitiatives);
      fs.writeFileSync(filePath, this.toFrontmatter({ ...entry, category: '' }) + cleanContent + referencedBy, 'utf8');
      this.updateIndices();
      return filePath;
    }
    const cat = this.sanitizeName(category);
    const filePath = path.join(this.dir, cat, `${entryId}.md`);

    if (!fs.existsSync(filePath)) {
      throw new Error(`Wiki entry not found: ${cat}/${entryId}`);
    }

    entry.updated = new Date().toISOString().split('T')[0];
    // Strip any existing auto-generated Referenced By section before regenerating
    const cleanContent = this.stripReferencedBySection(entry.content);
    const referencedBy = this.generateReferencedBySection(entry.relatedInitiatives);
    const content = this.toFrontmatter(entry) + cleanContent + referencedBy;
    fs.writeFileSync(filePath, content, 'utf8');
    this.updateIndices();
    return filePath;
  }

  addRelatedInitiative(category: string, id: string, initiativeId: string): string {
    const entry = this.read(category, id);
    if (!entry) {
      throw new Error(`Wiki entry not found: ${category}/${id}`);
    }
    if (!entry.relatedInitiatives.includes(initiativeId)) {
      entry.relatedInitiatives.push(initiativeId);
      entry.updated = new Date().toISOString().split('T')[0];
    }
    return this.update(category, id, entry);
  }

  addRelatedInitiativeByRef(ref: string, initiativeId: string): string {
    const parts = ref.split('/').filter(Boolean);
    if (parts.length === 1) {
      const id = parts[0].replace(/\.md$/, '');
      const entry = this.readRoot(id);
      if (!entry) throw new Error(`Wiki entry not found: ${ref}`);
      if (!entry.relatedInitiatives.includes(initiativeId)) {
        entry.relatedInitiatives.push(initiativeId);
        entry.updated = new Date().toISOString().split('T')[0];
      }
      return this.update('', id, entry);
    }
    if (parts.length === 2) return this.addRelatedInitiative(parts[0], parts[1].replace(/\.md$/, ''), initiativeId);
    throw new Error(`Invalid wikiSlug format: ${ref}. Expected id or category/id`);
  }

  getReferencedBy(category: string, id: string): string[] {
    const entryId = this.sanitizeName(id);
    const cat = this.isRootCategory(category) ? '' : this.sanitizeName(category);
    const wikiRef = cat ? `${cat}/${entryId}` : entryId;
    const initiativeIds: string[] = [];

    for (const filePath of this.listInitiativeFiles()) {
      try {
        const content = fs.readFileSync(filePath, 'utf8');
        const refs = this.parseRelatedWiki(content);
        if (refs.includes(wikiRef)) {
          // Extract initiative id from frontmatter
          const front = parseFrontmatter(content);
          if (front.id) {
            initiativeIds.push(front.id);
          }
        }
      } catch {
        // Ignore unreadable initiative files
      }
    }
    return initiativeIds;
  }

  private extractWikiRefs(content: string): string[] {
    const refs: string[] = [];
    // Match [[category/id]] wiki links
    const bracketMatches = content.matchAll(/\[\[([^\]]+)\/([^\]]+)\]\]/g);
    for (const match of bracketMatches) {
      refs.push(`${match[1]}/${match[2]}`);
    }
    // Match [text](category/id) markdown links that look like wiki refs
    const linkMatches = content.matchAll(/\[([^\]]*)\]\(([^)]+)\)/g);
    for (const match of linkMatches) {
      const href = match[2];
      // Only consider links that look like category/id (single slash, no protocol)
      if (!href.includes('://') && !href.startsWith('http') && href.split('/').length === 2) {
        const parts = href.split('/');
        if (parts[0] && parts[1]) {
          refs.push(href);
        }
      }
    }
    return [...new Set(refs)]; // deduplicate
  }

  addWikiCrossRef(fromCategory: string, fromId: string, toCategory: string, toId: string): string {
    const fromEntry = this.read(fromCategory, fromId);
    if (!fromEntry) {
      throw new Error(`Wiki entry not found: ${fromCategory}/${fromId}`);
    }
    const toRef = `${toCategory}/${toId}`;
    if (!fromEntry.relatedWiki) {
      fromEntry.relatedWiki = [];
    }
    if (!fromEntry.relatedWiki.includes(toRef)) {
      fromEntry.relatedWiki.push(toRef);
      fromEntry.updated = new Date().toISOString().split('T')[0];
    }
    return this.update(fromCategory, fromId, fromEntry);
  }

  delete(category: string, id: string): void {
    const entryId = this.sanitizeName(id);
    if (this.isRootCategory(category)) {
      this.assertRootWritable(entryId);
      const filePath = path.join(this.dir, `${entryId}.md`);
      if (fs.existsSync(filePath)) {
        fs.unlinkSync(filePath);
        this.updateIndices();
      }
      return;
    }
    const cat = this.sanitizeName(category);
    const filePath = path.join(this.dir, cat, `${entryId}.md`);
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
      this.updateIndices();
    }
  }

  list(category?: string): WikiEntry[] {
    if (category && this.sanitizeName(category) === '_obsidian') return [];
    const categories = category
      ? [this.sanitizeName(category)]
      : this.categoryDirs();

    const entries: WikiEntry[] = [];
    if (!category) {
      for (const filePath of this.rootWikiFiles()) {
        try {
          const entry = this.readRoot(path.basename(filePath, '.md'));
          if (entry) entries.push(entry);
        } catch {
        }
      }
    }
    for (const cat of categories) {
      const catDir = path.join(this.dir, cat);
      if (!fs.existsSync(catDir)) continue;
      const files = fs.readdirSync(catDir).filter(f => f.endsWith('.md') && f !== 'INDEX.md');
      for (const fileName of files) {
        try {
          const entry = this.read(cat, fileName.replace(/\.md$/, ''));
          if (entry) entries.push(entry);
        } catch {
        }
      }
    }
    return entries.sort((a, b) => `${a.category}/${a.id}`.localeCompare(`${b.category}/${b.id}`));
  }

  syncIndices(): string[] {
    if (this.contract.wikiIndexOwner !== 'harness') {
      return [];
    }
    this.updateIndices();
    const paths = [path.join(this.dir, 'INDEX.md')];
    const categories = this.categoryDirs();
    for (const category of categories) {
      paths.push(path.join(this.dir, category, 'INDEX.md'));
    }
    return paths;
  }

  findRelated(queryTags: string[]): WikiEntry[] {
    return this.list().filter(entry => entry.tags.some(t => queryTags.includes(t)));
  }

  stub(category: string, id: string, title?: string, template?: string): { success: boolean; existing?: boolean; filePath: string } {
    const entryId = this.sanitizeName(id);
    if (this.isRootCategory(category)) {
      this.assertRootWritable(entryId);
      const filePath = path.join(this.dir, `${entryId}.md`);
      if (fs.existsSync(filePath)) return { success: false, existing: true, filePath };
      const date = new Date().toISOString().split('T')[0];
      const stubContent = template || this.defaultStubTemplate(title || entryId, '', entryId, date);
      fs.writeFileSync(filePath, stubContent, 'utf8');
      this.updateIndices();
      return { success: true, filePath };
    }
    const cat = this.sanitizeName(category);
    const categoryDir = path.join(this.dir, cat);
    fs.mkdirSync(categoryDir, { recursive: true });
    const filePath = path.join(categoryDir, `${entryId}.md`);

    if (fs.existsSync(filePath)) {
      return { success: false, existing: true, filePath };
    }

    const date = new Date().toISOString().split('T')[0];
    const stubTitle = title || entryId;
    const stubContent = template || this.defaultStubTemplate(stubTitle, cat, entryId, date);

    fs.writeFileSync(filePath, stubContent, 'utf8');
    this.updateIndices();
    return { success: true, filePath };
  }

  private defaultStubTemplate(title: string, category: string, id: string, date: string): string {
    return `---
id: "${id}"
title: "${title}"
category: "${category}"
created: "${date}"
updated: "${date}"
related_initiatives: []
tags: []
---

## Overview

<!-- Add overview here -->

## Details

<!-- Add details here -->

## References

- Linked from initiative: <!-- initiative ids will be auto-populated -->
`;
  }

  validate(): { valid: boolean; errors: string[]; warnings: string[] } {
    const errors: string[] = [];
    const warnings: string[] = [];
    const referencedWiki = this.referencedWikiRefs();
    const categories = this.categoryDirs();

    // Check for broken related_wiki links in initiatives
    const initiativesDir = path.join(path.dirname(this.dir), 'initiatives');
    if (fs.existsSync(initiativesDir)) {
      for (const filePath of this.listInitiativeFiles()) {
        try {
          const content = fs.readFileSync(filePath, 'utf8');
          for (const ref of this.parseRelatedWiki(content)) {
            if (!this.readByRef(ref)) {
              errors.push(`Initiative ${path.relative(initiativesDir, filePath)} references missing wiki entry: ${ref}`);
            }
          }
        } catch {
          // Ignore unreadable initiative files
        }
      }
    }

    for (const category of categories) {
      const catDir = path.join(this.dir, category);
      const files = fs.readdirSync(catDir).filter(f => f.endsWith('.md') && f !== 'INDEX.md');
      for (const fileName of files) {
        const relativeName = `${category}/${fileName}`;
        try {
          const entry = this.parseWikiEntry(fs.readFileSync(path.join(catDir, fileName), 'utf8'));
          if (!entry.id) errors.push(`${relativeName} missing id`);
          if (!entry.title) errors.push(`${relativeName} missing title`);
          if (!entry.category) errors.push(`${relativeName} missing category`);
          const hasSourceInitiatives = Array.isArray(entry.sourceInitiatives) && entry.sourceInitiatives.length > 0;
          const isStable = entry.lifecycle === 'stable';
          const isStandaloneCategory = this.standaloneCategories.has(entry.category);
          const isReferencedByInitiative = entry.id && entry.category && referencedWiki.has(`${entry.category}/${entry.id}`);
          if (entry.id && entry.category && !isStable && !isStandaloneCategory && !hasSourceInitiatives && !isReferencedByInitiative) {
            warnings.push(`${relativeName} is not referenced by any initiative`);
          }
        } catch (err: any) {
          errors.push(`${relativeName} invalid wiki entry format: ${err.message || String(err)}`);
        }
      }
    }

    for (const filePath of this.rootWikiFiles()) {
      const relativeName = path.basename(filePath);
      try {
        const entry = this.readRoot(path.basename(filePath, '.md'));
        if (!entry) continue;
        if (!entry.id) errors.push(`${relativeName} missing id`);
        if (!entry.title) errors.push(`${relativeName} missing title`);
      } catch (err: any) {
        errors.push(`${relativeName} invalid wiki entry format: ${err.message || String(err)}`);
      }
    }

    return { valid: errors.length === 0, errors, warnings };
  }

  private rootWikiFiles(): string[] {
    if (!fs.existsSync(this.dir)) return [];
    return fs.readdirSync(this.dir, { withFileTypes: true })
      .filter(entry => entry.isFile() && entry.name.endsWith('.md') && entry.name !== 'INDEX.md')
      .map(entry => path.join(this.dir, entry.name));
  }

  private categoryDirs(): string[] {
    if (!fs.existsSync(this.dir)) return [];
    return fs.readdirSync(this.dir).filter(f => f !== '_obsidian' && fs.statSync(path.join(this.dir, f)).isDirectory());
  }

  private listInitiativeFiles(): string[] {
    const initiativesDir = path.join(path.dirname(this.dir), 'initiatives');
    if (!fs.existsSync(initiativesDir)) return [];
    const files: string[] = [];
    for (const entry of fs.readdirSync(initiativesDir, { withFileTypes: true })) {
      if (entry.isFile() && entry.name.endsWith('.md') && entry.name !== 'INDEX.md') files.push(path.join(initiativesDir, entry.name));
      if (entry.isDirectory() && entry.name !== 'archive' && entry.name !== '_archive') {
        const statusPath = path.join(initiativesDir, entry.name, '_status.md');
        if (fs.existsSync(statusPath)) files.push(statusPath);
      }
    }
    return files;
  }

  checkConsistency(): { consistent: boolean; missing: string[]; orphans: string[]; stale: boolean } {
    const missing: string[] = [];
    const orphans: string[] = [];
    let stale = false;

    if (this.contract.wikiIndexOwner !== 'harness') {
      if (this.contract.wikiIndexMode === 'canonical-lowercase' && !fs.existsSync(path.join(this.dir, 'index.md'))) {
        missing.push('wiki/index.md');
      }
      return {
        consistent: missing.length === 0,
        missing,
        orphans,
        stale
      };
    }

    const categories = this.categoryDirs();

    // Check root INDEX.md
    const rootIndexPath = path.join(this.dir, 'INDEX.md');
    if (!fs.existsSync(rootIndexPath)) {
      missing.push('wiki/INDEX.md');
    } else {
      const rootIndexMtime = fs.statSync(rootIndexPath).mtimeMs;
      const rootContent = fs.readFileSync(rootIndexPath, 'utf8');
      // Extract category names from root index: [category](category/INDEX.md)
      const listedCategories = new Set(Array.from(rootContent.matchAll(/\[([^\]]+)\]\([^)]*INDEX\.md\)/g)).map(m => m[1]));

      for (const category of categories) {
        if (!listedCategories.has(category)) {
          orphans.push(`wiki/${category}/ (missing from root INDEX)`);
        }
      }
    }

    // Check per-category INDEX.md files
    for (const category of categories) {
      const catDir = path.join(this.dir, category);
      const catIndexPath = path.join(catDir, 'INDEX.md');
      const catFiles = fs.readdirSync(catDir).filter(f => f.endsWith('.md') && f !== 'INDEX.md');

      if (!fs.existsSync(catIndexPath)) {
        missing.push(`wiki/${category}/INDEX.md`);
        continue;
      }

      const catIndexMtime = fs.statSync(catIndexPath).mtimeMs;
      const catContent = fs.readFileSync(catIndexPath, 'utf8');

      // Build set of known IDs from the INDEX. Prefer the link target (`[Title](id.md)`);
      // fall back to the normalized line text for legacy plain `- Title` or `- id` entries.
      const knownIds = new Set<string>();
      for (const m of catContent.matchAll(/^- (.+)$/gm)) {
        const line = m[1].trim();
        const linkMatch = line.match(/^\[([^\]]+)\]\(([^)]+)\.md\)$/);
        if (linkMatch) {
          knownIds.add(linkMatch[2].trim().toLowerCase());
        } else {
          knownIds.add(line.toLowerCase().replace(/\s+/g, '-'));
        }
      }

      // Build alias set for each on-disk file: filename, frontmatter id, frontmatter title.
      const fileAliases = new Map<string, Set<string>>();
      for (const fileName of catFiles) {
        const filePath = path.join(catDir, fileName);
        const filenameId = fileName.replace('.md', '');
        const aliases = new Set<string>([filenameId.toLowerCase()]);
        try {
          const content = fs.readFileSync(filePath, 'utf8');
          const fmMatch = content.match(/---\n([\s\S]*?)\n---/);
          if (fmMatch) {
            const idMatch = fmMatch[1].match(/^id:\s*"?([^"\n]+)"?/m);
            if (idMatch) aliases.add(idMatch[1].trim().toLowerCase());
            const titleMatch = fmMatch[1].match(/^title:\s*"?([^"\n]+)"?/m);
            if (titleMatch) {
              aliases.add(titleMatch[1].trim().toLowerCase().replace(/\s+/g, '-'));
            }
          }
        } catch {
          // unreadable file: only filename alias is available
        }
        fileAliases.set(filenameId, aliases);
      }

      // Missing: INDEX lists an id that no on-disk file matches (via any alias).
      for (const known of knownIds) {
        const found = Array.from(fileAliases.values()).some(aliases => aliases.has(known));
        if (!found) {
          missing.push(`wiki/${category}/${known}.md`);
        }
      }

      // Orphan: on-disk file whose none of its aliases appears in the INDEX.
      for (const [filenameId, aliases] of fileAliases) {
        const found = Array.from(aliases).some(a => knownIds.has(a));
        if (!found) {
          orphans.push(`wiki/${category}/${filenameId}.md`);
        }
      }

      for (const fileName of catFiles) {
        const filePath = path.join(catDir, fileName);
        const fileMtime = fs.statSync(filePath).mtimeMs;
        if (fileMtime > catIndexMtime) {
          stale = true;
        }
      }
    }

    return {
      consistent: missing.length === 0 && orphans.length === 0 && !stale,
      missing,
      orphans,
      stale
    };
  }

  private writeIndexMeta(): void {
    const metaPath = path.join(path.dirname(this.dir), '.index-meta.json');
    const meta = { lastSync: new Date().toISOString() };
    fs.writeFileSync(metaPath, JSON.stringify(meta, null, 2), 'utf8');
  }

  private updateIndices(): void {
    if (this.contract.wikiIndexOwner !== 'harness') {
      return;
    }
    const categories = this.categoryDirs();

    // Per-category indices
    for (const category of categories) {
      const catDir = path.join(this.dir, category);
      const files = fs.readdirSync(catDir).filter(f => f.endsWith('.md') && f !== 'INDEX.md');
      const lines = files.map(f => {
        const content = fs.readFileSync(path.join(catDir, f), 'utf8');
        const frontmatterMatch = content.match(/---\n([\s\S]*?)\n---/);
        let title: string | null = null;
        let id: string | null = null;
        if (frontmatterMatch) {
          const idMatch = frontmatterMatch[1].match(/^id:\s*"?([^"\n]+)"?/m);
          if (idMatch) id = idMatch[1].trim();
          const titleMatch = frontmatterMatch[1].match(/^title:\s*"?([^"\n]+)"?/m);
          if (titleMatch) title = titleMatch[1].trim();
        }
        const safeTitle = title || f.replace('.md', '');
        const safeId = id || f.replace('.md', '');
        return `- [${safeTitle}](${safeId}.md)`;
      });
      const index = `# ${category}\n\n${lines.join('\n') || 'No entries yet.'}`;
      fs.writeFileSync(path.join(catDir, 'INDEX.md'), index, 'utf8');
    }

    // Root wiki index
    const catLines = categories.map(c => `- [${c}](${c}/INDEX.md)`);
    const rootIndex = `# Wiki\n\n## Categories\n\n${catLines.join('\n')}`;
    fs.writeFileSync(path.join(this.dir, 'INDEX.md'), rootIndex, 'utf8');
    this.writeIndexMeta();
  }
}
